config/routes.rb
Rails.application.routes.draw do
  get 'contacts' => 'contacts#new'

  get 'contacts/create'

  get 'about' => 'abouts#index'

  namespace :admin do
  get 'login' => 'sessions#new', :as => 'login'
  end

  namespace :admin do
  get 'logout' => 'sessions#destroy', :as => 'logout'
  end

  namespace :admin do
  get 'sessions/create'
  end

  namespace :admin do
  get 'users/new'
  end

  namespace :admin do
  get 'users/create'
  end

  namespace :admin do
  get 'users/edit'
  end

  namespace :admin do
  get 'users/update'
  end

  namespace :admin do
  get 'users/destroy'
  end

  namespace :admin do
  get 'users/index'
  end

  namespace :admin do
  get 'users/show'
  end

  namespace :admin do
  get 'comments/destroy'
  end

  get 'comments/new'

  namespace :admin do
  get 'categories/new'
  end

  namespace :admin do
  get 'categories/create'
  end

  namespace :admin do
  get 'categories/edit'
  end

  namespace :admin do
  get 'categories/update'
  end

  namespace :admin do
  get 'categories/destroy'
  end

  namespace :admin do
  get 'categories/index'
  end

  namespace :admin do
  get 'categories/show'
  end

  get 'categories/show'

  namespace :admin do
  get 'posts/new'
  end

  namespace :admin do
  get 'posts/create'
  end

  namespace :admin do
  get 'posts/edit'
  end

  namespace :admin do
  get 'posts/update'
  end

  namespace :admin do
  get 'posts/destroy'
  end

  namespace :admin do
  get 'posts/index'
  end

  namespace :admin do
  get 'posts/show'
  end

  get 'posts/index'

  get 'posts/show'

  resources :posts, :categories

  resources "contacts", only:[:new, :create]

  namespace :admin do
    resources :posts, :categories, :comments, :users, :sessions
  end

  resources :post do
    resources :comments
  end
  root 'posts#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :posts

  validates :name, presence: true

  def self.search(query)
    where("name like ?", "%#{query}%")
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::ApplicationController
  before_filter :verify_logged_in
  
  def new
    @page_title = 'Add Category'
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = 'Category Created'
      redirect_to admin_categories_path
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = 'Category Updated'
      redirect_to admin_categories_path
    else
      render 'new'
    end
  end

  def destroy
    @category = Category.find(params[:id])
    if @category.destroy
      flash[:notice] = 'Category Removed'
      redirect_to admin_categories_path
    else
      render 'new'
    end
  end

  def index
    if params[:search]
      @categories = Category.search(params[:search]).all.order('created_at DESC').paginate(:per_page => 2, :page => params[:page])
    else
      @categories = Category.all.order('created_at DESC').paginate(:per_page => 2, :page => params[:page])
    end
  end

  def show
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
    @categories = Category.all
    @posts = @category.posts
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/edit.html.erb
<h2>Edit Category</h2>

<%= form_for [:admin, @category] do |f| %>
  <!-- check for errors -->
  <% if @category.errors.any? %>
    <% @category.errors.full_messages.each do |msg| %>
      <!-- show errors -->
      <div class="alert alert-danger">
        <%= msg %>
      </div>
    <%end%>
  <%end%>
  <div class="form-group">
    <%= f.label :name %><br/>
    <%= f.text_field :name, class:'form-control' %><br/>
  </div>

  <%= f.submit "Submit", class:'btn btn-primary' %>
  <%= link_to "Cancel", admin_categories_path, class:'btn btn-default' %>
<%end%>

app/views/admin/categories/index.html.erb
<h2 class="page-header">Manage Categories <%= link_to "Create New", new_admin_category_path, class:'btn btn-success pull-right'%></h2>
<table class="table table-stripped">
  <tr>
    <th>Category Title</th>
    <th>Created Date</th>
    <th>Action</th>
  </tr>
  <% @categories.each do |category| %>
    <tr>
      <td><%= category.name %></td>
      <td><%= category.created_at.to_time.strftime('%B %e at %l:%M %p') %></td>
      <td>
        <%= link_to "Edit", edit_admin_category_path(category), class:'btn btn-success'%>
        <%= link_to "Delete", admin_category_path(category), class:'btn btn-danger', method: :delete, data: {confirm: 'Are you sure'}%>
      </td>
    </tr>
  <%end%>
</table>
<%= will_paginate @categories %>

app/views/admin/categories/new.html.erb
<h2>Add Category</h2>

<%= form_for [:admin, @category] do |f| %>
  <!-- check for errors -->
  <% if @category.errors.any? %>
    <% @category.errors.full_messages.each do |msg| %>
      <!-- show errors -->
      <div class="alert alert-danger">
        <%= msg %>
      </div>
    <%end%>
  <%end%>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class:'form-control' %>
  </div>

  <%= f.submit "Submit", class:'btn btn-primary' %>
  <%= link_to "Cancel", admin_categories_path, class:'btn btn-default' %>
<%end%>