config/routes.rb
Rails.application.routes.draw do
  get 'contacts' => 'contacts#new'

  get 'contacts/create'

  get 'about' => 'abouts#index'

  namespace :admin do
  get 'login' => 'sessions#new', :as => 'login'
  end

  namespace :admin do
  get 'logout' => 'sessions#destroy', :as => 'logout'
  end

  namespace :admin do
  get 'sessions/create'
  end

  namespace :admin do
  get 'users/new'
  end

  namespace :admin do
  get 'users/create'
  end

  namespace :admin do
  get 'users/edit'
  end

  namespace :admin do
  get 'users/update'
  end

  namespace :admin do
  get 'users/destroy'
  end

  namespace :admin do
  get 'users/index'
  end

  namespace :admin do
  get 'users/show'
  end

  namespace :admin do
  get 'comments/destroy'
  end

  get 'comments/new'

  namespace :admin do
  get 'categories/new'
  end

  namespace :admin do
  get 'categories/create'
  end

  namespace :admin do
  get 'categories/edit'
  end

  namespace :admin do
  get 'categories/update'
  end

  namespace :admin do
  get 'categories/destroy'
  end

  namespace :admin do
  get 'categories/index'
  end

  namespace :admin do
  get 'categories/show'
  end

  get 'categories/show'

  namespace :admin do
  get 'posts/new'
  end

  namespace :admin do
  get 'posts/create'
  end

  namespace :admin do
  get 'posts/edit'
  end

  namespace :admin do
  get 'posts/update'
  end

  namespace :admin do
  get 'posts/destroy'
  end

  namespace :admin do
  get 'posts/index'
  end

  namespace :admin do
  get 'posts/show'
  end

  get 'posts/index'

  get 'posts/show'

  resources :posts, :categories

  resources "contacts", only:[:new, :create]

  namespace :admin do
    resources :posts, :categories, :comments, :users, :sessions
  end

  resources :post do
    resources :comments
  end
  root 'posts#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :posts

  validates :name, presence: true

  def self.search(query)
    where("name like ?", "%#{query}%")
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :category
  belongs_to :user
  has_many :comments

  validates :title, presence: true
  validates :category_id, presence: true
  validates :body, presence: true

  has_attached_file :image, :default_url => ":style/default.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  def self.search(query)
    where("title like ? OR body like ?", "%#{query}%","%#{query}%")
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  before_save :encrypt_password
  has_many :posts

  validates :name, presence: true
  validates :email, presence: true
  validates :password, presence: true
  validates :password, confirmation: true

  def self.authenticate(email, password)
      user = find_by_email(email)
      if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
        user
      else
        nil
      end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  def self.search(query)
    where("name like ?", "%#{query}%")
  end
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  def index
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
    before_filter :verify_logged_in

    def new
      @page_title = 'Add user'
      @user = User.new
    end

    def create
      @user = User.new(user_params)
      if @user.save
        flash[:notice] = 'User Created'
        redirect_to admin_users_path
      else
        render 'new'
      end
    end

    def edit
      @user = User.find(params[:id])
    end

    def update
      @user = User.find(params[:id])
      if @user.update(user_params)
        flash[:notice] = 'User Updated'
        redirect_to admin_users_path
      else
        render 'new'
      end
    end

    def destroy
      @user = User.find(params[:id])
      if @user.destroy
        flash[:notice] = 'User Removed'
        redirect_to admin_users_path
      else
        render 'new'
      end
    end

    def index
      if params[:search]
        @users = User.search(params[:search]).all.order('created_at DESC').paginate(:per_page => 2, :page => params[:page])
      else
        @users = User.all.order('created_at DESC').paginate(:per_page => 2, :page => params[:page])
      end
    end

    def show
    end

    private
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
    @categories = Category.all
    @posts = @category.posts
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)

    flash[:notice] = 'Comment Added'

    redirect_to post_path(@post)
  end

  private
    def comment_params
      params.require(:comment).permit(:name, :email, :body, :post_id)
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
  end

  def create
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    if params[:search]
      @posts = Post.search(params[:search]).all.order('created_at DESC').paginate(:per_page => 5, :page => params[:page])
    else
      @posts = Post.all.order('created_at DESC').paginate(:per_page => 5, :page => params[:page])
    end
    @categories = Category.all
  end

  def show
    @post = Post.find(params[:id])
    @categories = Category.all
    @comment = Comment.new
    @comments = Comment.all
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/users/edit.html.erb
<h2>Edit User</h2>

<%= form_for [:admin, @user] do |f| %>
  <!-- check for errors -->
  <% if @user.errors.any? %>
    <% @user.errors.full_messages.each do |msg| %>
      <!-- show errors -->
      <div class="alert alert-danger">
        <%= msg %>
      </div>
    <%end%>
  <%end%>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :new_password %>
    <%= f.password_field :password, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :new_password_confirmation %>
    <%= f.password_field :password_confirmation, class:'form-control' %>
  </div>

  <%= f.submit "Submit", class:'btn btn-primary' %>
  <%= link_to "Cancel", admin_users_path, class:'btn btn-default' %>
<%end%>

app/views/admin/users/index.html.erb
<h2 class="page-header">Manage Users <%= link_to "Create New", new_admin_user_path, class:'btn btn-success pull-right' %></h2>
<% if @users.exists? %>
  <table class="table table-stripped">
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Date Created</th>
      <th>Actions</th>
    </tr>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.created_at.to_time.strftime('%B %e at %l:%M %p') %></td>
        <td>
          <%= link_to "Edit", edit_admin_user_path(user), class:'btn btn-success'%>
          <%= link_to "Delete", admin_user_path(user), class:'btn btn-danger', method: :delete, data: {confirm: 'Are you sure'}%>
        </td>
      </tr>
    <%end%>
  </table>
  <%= will_paginate @users %>
<% else %>
  <p>There are no users</p>
<%end%>

app/views/admin/users/new.html.erb
<h2>Add New User</h2>

<%= form_for [:admin, @user] do |f| %>
  <!-- check for errors -->
  <% if @user.errors.any? %>
    <% @user.errors.full_messages.each do |msg| %>
      <!-- show errors -->
      <div class="alert alert-danger">
        <%= msg %>
      </div>
    <%end%>
  <%end%>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class:'form-control' %>
  </div>

  <%= f.submit "Submit", class:'btn btn-primary' %>
  <%= link_to "Cancel", admin_users_path, class:'btn btn-default' %>
<%end%>